### ISSUE TITLE
unsupported operand type(s)

### ISSUE THREAD

**Issue by jungle-boogie** [LFlare/ZeroTierNC#1]
What do I need to do in order to run this?

```
Traceback (most recent call last):
  File "bin/zerotier-nc.py", line 388, in <module>
    main()
  File "bin/zerotier-nc.py", line 295, in main
    set_headers()
  File "bin/zerotier-nc.py", line 85, in set_headers
    with open(get_filepath()+"/authtoken.secret") as file:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "bin/zerotier-nc.py", line 57, in save_ctrlr
    with open(get_filepath()+"/ctrlr.pickle", "wb") as file:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by jungle-boogie** [comment]
```
Python 3.5.3 (default, May 18 2017, 01:29:37)
[GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)] on freebsd12
```

**Comment by LFlare** [comment]
What are you trying to do?

**Comment by jungle-boogie** [comment]
I am running `zerotier-nc.py' and `python3 zerotier-nc.py` that's it.

**Comment by LFlare** [comment]
@jungle-boogie, okay, what do you want to do? Try running `./zerotier-nc.py -h`

**Comment by jungle-boogie** [comment]
@LFlare,

Looks like the same mess.

```
 ./bin/zerotier-nc.py -h
Traceback (most recent call last):
  File "./bin/zerotier-nc.py", line 388, in <module>
    main()
  File "./bin/zerotier-nc.py", line 295, in main
    set_headers()
  File "./bin/zerotier-nc.py", line 85, in set_headers
    with open(get_filepath()+"/authtoken.secret") as file:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "./bin/zerotier-nc.py", line 57, in save_ctrlr
    with open(get_filepath()+"/ctrlr.pickle", "wb") as file:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by LFlare** [comment]
@jungle-boogie, what are you running this on? Windows?

**Comment by jungle-boogie** [comment]
hi @LFlare, no freebsd 12-current. It's actually trueOS: https://www.trueos.org

**Comment by LFlare** [comment]
@jungle-boogie, can you verify that `/var/lib/zerotier-one` is your ZeroTierOne file folder?

**Comment by jungle-boogie** [comment]
hi @LFlare, The binary is here: `/usr/local/bin/zerotier-idtool -> /usr/local/sbin/zerotier-one`

**Comment by LFlare** [comment]
@jungle-boogie, I don't mean the binary, I mean the data directory. Can you check your directories at https://www.zerotier.com/manual.shtml#4?

**Comment by jungle-boogie** [comment]
hi @LFlare, oh, my mistake. Sorry.

yes, `/var/db/zerotier-one` is correct

**Comment by jungle-boogie** [comment]
I have modified the script to use python3.5:
`#! /usr/bin/env python3.5`

**Comment by LFlare** [comment]
@jungle-boogie, modifying the script header to use `python3.5` doesn't matter and won't change anything unless `python3` is not a valid symlink to `python3.$latestver`. In any case, try my latest commit, it should fix your issues.

**Comment by jungle-boogie** [comment]
hi @LFlare,

Right, just pointing out a slight modification I did.

Here's the results of the test:

```
./zerotier-nc.py -h
Traceback (most recent call last):
  File "./zerotier-nc.py", line 396, in <module>
    main()
  File "./zerotier-nc.py", line 300, in main
    set_headers()
  File "./zerotier-nc.py", line 87, in set_headers
    with open(get_filepath()+"/authtoken.secret") as file:
  File "./zerotier-nc.py", line 76, in get_filepath
    elif platfor.system() == "FreeBSD":
NameError: name 'platfor' is not defined
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "./zerotier-nc.py", line 57, in save_ctrlr
    with open(get_filepath()+"/ctrlr.pickle", "wb") as file:
  File "./zerotier-nc.py", line 76, in get_filepath
    elif platfor.system() == "FreeBSD":
NameError: name 'platfor' is not defined
```

**Comment by LFlare** [comment]
@jungle-boogie, try the newest of the newest commit.

**Comment by jungle-boogie** [comment]
Hi @LFlare,

That's good now.

Do you think sudo is really necessary to execute the help?

```
% ./zerotier-nc.py -h
Traceback (most recent call last):
  File "./zerotier-nc.py", line 398, in <module>
    main()
  File "./zerotier-nc.py", line 302, in main
    set_headers()
  File "./zerotier-nc.py", line 89, in set_headers
    with open(get_filepath()+"/authtoken.secret") as file:
PermissionError: [Errno 13] Permission denied: '/var/db/zerotier-one/authtoken.secret'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "./zerotier-nc.py", line 57, in save_ctrlr
    with open(get_filepath()+"/ctrlr.pickle", "wb") as file:
PermissionError: [Errno 13] Permission denied: '/var/db/zerotier-one/ctrlr.pickle'
```

**Comment by LFlare** [comment]
@jungle-boogie, yes, sudo is required simply because that ZeroTier's auth token is owned by root as a security measure.

**Comment by LFlare** [comment]
If there's no other issues, I'll close this now. Re-open if you got other issues.

**Comment by jungle-boogie** [comment]
So far no other issues.

Thanks for fixing this and supporting FreeBSD.
