### ISSUE TITLE
openBSD: unsupported operand

### ISSUE THREAD

**Issue by jungle-boogie** [LFlare/ZeroTierNC#3]
Hi,

Similar to #1, but this is pertaining to OpenBSD:

```
Traceback (most recent call last):
  File "./zerotier-nc.py", line 398, in <module>
    main()
  File "./zerotier-nc.py", line 302, in main
    set_headers()
  File "./zerotier-nc.py", line 89, in set_headers
    with open(get_filepath()+"/authtoken.secret") as file:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "./zerotier-nc.py", line 57, in save_ctrlr
    with open(get_filepath()+"/ctrlr.pickle", "wb") as file:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

`/var/db/zerotier-one` contains the data directory

**Comment by LFlare** [comment]
@jungle-boogie, that is strange, so strange. Could you run the following few commands in the Python console for me?

    $ python3
    >>> import platform
    >>> platform.system()

Paste the output here.

**Comment by jungle-boogie** [comment]
Once again, You've fixed it!
